#!/bin/bash

# Get start time
STARTTIME=$(date +%s)

# Push to BitBucket
if [ -z "$1" ]
then
	echo -e "\nError: commit message empty. Please pass a message as an arg.\n"
else
	git add -A
	git commit -m "$1"
	git push origin master
fi

# SSH into server and update
cd ../..
ssh -tt -i "<pem_file>" <server_user_url> << EOF
  cd <site-folder>
	rm src/public/_css/style.css
	rm src/public/_javascript/scripts.js
  git pull
	gulp
	npm run build
	pm2 delete -s server || :
	pm2 start src/server-compiled.js
	sudo service nginx restart
  exit
EOF

# Get end time and difference
ENDTIME=$(date +%s)
DIFFERENCE=$(($ENDTIME-$STARTTIME))

# Echo finished with time
echo -e "\n  Done in $DIFFERENCE seconds!\n"
